#!/bin/sh
if [[ $# == 0 ]]; then
    git add . && git commit -m $(date +%Y/%m/%d) && git push origin $(git rev-parse --abbrev-ref HEAD)
else
    case $1 in
    hooks)
        husky install && echo "_" >.husky/.gitignore && husky add .husky/commit-msg 'commitlint --edit "$1"' && husky add .husky/pre-commit "lint-staged"
        ;;
    reset)
        git add . && git reset HEAD --hard
        ;;
    work)
        git config user.name "liaoweishi" && git config user.email "liaoweishi@bdsecurity.com"
        ;;
    personal)
        git config user.name "xhwhis" && git config user.email "hi@whis.me"
        ;;
    push)
        git add . && git commit -m $(date +%Y/%m/%d) && git push origin $(git rev-parse --abbrev-ref HEAD)
        ;;
    *)
        echo 'fgit: no such subcommand: "'$1'"'
        ;;
    esac
fi
