#!/bin/sh
deploy() {
    case $1 in
        github.io)
            rm -rf build
            git clone git@github.com:xhwhis/xhwhis.github.io.git public
            hugo -D
            cd public
            fgit
            cd ..
            git add .
            git reset --hard
            ;;
        xhwhis.com)
            rm -rf build
            git clone git@github.com:xhwhis/xhwhis.com.git public
            hugo -D
            cd public
            fgit
            cd ..
            git add .
            git reset --hard
            ;;
        whis.me)
            rm -rf build
            git clone git@github.com:xhwhis/whis.me.git public
            hugo -D
            cd public
            fgit
            cd ..
            git add .
            git reset --hard
            ;;
        *)
            echo "domain error"
            ;;
    esac
}

if [[ $# == 0 ]]; then
    deploy github.io
else
    deploy $1
fi
