#!/usr/bin/bash
pick() {
    if [ -f "/etc/v2ray/$1_config.json" ]; then
        echo "    " | sudo -S cp /etc/v2ray/$1_config.json /etc/v2ray/config.json > /dev/null 2>&1
        echo "    " | sudo -S systemctl restart v2ray
        echo "success"
    else
        echo "pick: no such node: $1"
    fi
}
if [[ $# == 0 ]]; then
    read -p "pick the node: " node
    pick $node
else
    pick $1
fi
