#!/bin/sh
run() {
    if [[ -f $1 ]]; then
        file=$1
        name=${file%.*}
        type=${file#*.}
        case $type in
            c)
                if [[ $# == 1 ]]; then
                    clang $1 -o $name.out -lm -lpthread -lcurses -std=c11 && time ./$name.out && rm -f $name.out
                else
                    if [[ $2 == "<" ]]; then
                        clang $1 -o $name.out -lm -lpthread -lcurses -std=c11 && time ./$name.out < $3 && rm -f $name.out
                    elif [[ $2 == ">" ]]; then
                        clang $1 -o $name.out -lm -lpthread -lcurses -std=c11 && time ./$name.out > $3 && rm -f $name.out
                    else
                        para=`echo $* | cut -d " " -f 2-`
                        clang $1 -o $name.out -lm -lpthread -lcurses -std=c11 && time ./$name.out $para && rm -f $name.out
                    fi
                fi
                ;;
            cpp)
                if [[ $# == 1 ]]; then
                    clang++ $1 -o $name.out -lpthread -lcurses -std=c++11 && time ./$name.out && rm -f $name.out
                else
                    if [[ $2 == "<" ]]; then
                        clang++ $1 -o $name.out -lpthread -lcurses -std=c++11 && time ./$name.out < $3 && rm -f $name.out
                    elif [[ $2 == ">" ]]; then
                        clang++ $1 -o $name.out -lpthread -lcurses -std=c++11 && time ./$name.out > $3 && rm -f $name.out
                    else
                        para=`echo $* | cut -d " " -f 2-`
                        clang++ $1 -o $name.out -lpthread -lcurses -std=c++11 && time ./$name.out $para && rm -f $name.out
                    fi
                fi
                ;;
            py)
                python3 $1
                ;;
            sh)
                bash $1
                ;;
            zsh)
                zsh $1
                ;;
            java)
                javac $1 && java $name && rm -f $name.class
                ;;
            go)
                go run $1
                ;;
            html)
                open $1
                ;;
            swift)
                swift $1
                ;;
            *)
                echo "type error"
                ;;
        esac
    else
        echo "run: no such file: $1"
    fi
}
if [[ $# == 0 ]]; then
    all=`tail -2 ~/.zsh_history | head -1 | cut -d " " -f 3-`
    run $all
else
    run $*
fi
