#!/usr/bin/bash
run() {
    if [[ -f $1 ]]; then
        file=$1
        name=${file%.*}
        type=${file#*.}
        case $type in
            c)
                if [[ $# > 1 && -f $2 ]]; then
                    clang $1 -o $name.out -lm -lpthread -lcurses -std=c11 && time ./$name.out < $2 && rm -f $name.out
                else
                    clang $1 -o $name.out -lm -lpthread -lcurses -std=c11 && time ./$name.out && rm -f $name.out
                fi
                ;;
            cpp)
                if [[ $# > 1 && -f $2 ]]; then
                    clang++ $1 -o $name.out -lpthread -lcurses -std=c++11 && time ./$name.out < $2 && rm -f $name.out
                else
                    clang++ $1 -o $name.out -lpthread -lcurses -std=c++11 && time ./$name.out < $2 && rm -f $name.out
                fi
                ;;
            py)
                python $1
                ;;
            sh)
                bash $1
                ;;
            zsh)
                zsh $1
                ;;
            java)
                javac $1 && java $name && rm -f $name.class
                ;;
            html)
                google-chrome-stable $1
                ;;
            *)
                echo "type error"
                ;;
        esac
    else
        echo "run: no such file: $1"
    fi
}
if [[ $# == 0 ]]; then
    para=`tail -2 ~/.zsh_history | head -1 | cut -d " " -f 3-`
    run $para
else
    run $*
fi
